kk_pokedex
KondrashovKonstantin/pokedex pull request #1
Opened 2020-12-07 16:14 UTC by KondrashovKonstantin

2021-04-14 17:37 UTC, lupenq requested changes

2021-04-14 17:37 UTC, lupenq commented on components/PokemonCard/index.js
> +import './index.styl'
последним

2021-04-14 17:37 UTC, lupenq commented on components/PokemonCard/index.js
> +          Tag(type = tag key = tag)
Пробелы вокруг равно лишние, и переноси пропсы плиз

2021-04-14 17:37 UTC, lupenq commented on components/PokemonCard/index.styl
> +  flex 1
в сафари кстати flex 1 багует

2021-04-14 17:37 UTC, lupenq commented on components/PokemonCard/index.styl
> +  font-weight bold
Кидай bold в пропсы, и для размера шрифта юзай font() миксин

2021-04-14 17:37 UTC, lupenq commented on components/PokemonCard/index.styl
> +  font-size 16px
same(и юниты надо)

2021-04-14 17:37 UTC, lupenq commented on components/Tag/index.js
> +    Span.tag(
Можешь использовать компонент Tag из @ui

2021-04-14 17:37 UTC, lupenq commented on components/Tag/index.styl
> +  border-radius 4px
radius()

2021-04-14 17:37 UTC, lupenq commented on main/pages/Add/index.js
> +  const [height, setHeight] = useState()
Было бы удобней юзать useValue с объектом

2021-04-14 17:37 UTC, lupenq commented on main/pages/Add/index.js
> +        Span.label(styleName=showError?'error':null) Pokemon Name #{showError?'- this fields is required':null}
перенеси все нужное на новые строчки и через = чилдрены задавай

2021-04-14 17:37 UTC, lupenq commented on main/pages/Pokemons/PokemonCards/index.styl
> +  flex-direction row
Row компонент

2021-04-19 16:07 UTC, KondrashovKonstantin commented on components/Tag/index.js
> +    Span.tag(
Там боков много и кастомизация не оч, я специально писал кастомный

2021-09-06 20:16 UTC, merged